### ISSUE TITLE
Can't change parameters

### ISSUE THREAD

**Issue by rgarcia27** [amarinderthind/decontaminer#2]
Hey! I'm running decontaMiner with different parameters (filter_blastInfo) but it seems it's not letting me do it. 
The parameters I'm setting are -g5 -m2 -l50 and the output says:

Using L=50G =2 M=2
Processing...
...done !

I can change -g to whatever and keeps telling me that, although if I change the length, it shows the correct set up.

**Comment by rgarcia27** [comment]
In the filter_BlastInfo.sh script, section 2.1 is this line

if [[ ! (-z "$g" ) ]]; then
 gN=$m;
fi

so, maybe that's why.
Please let me know if this has a reason to be, or if I can simply change it to 

if [[ ! (-z "$g" ) ]]; then
 gN=$g;
fi

Thanks!

**Comment by marasangiovanni** [comment]
Hi, sorry for the late reply. Indeed the error is the one you spotted, and the solution is the correct one. Thanks, I'll change the code ASAP.
