### ISSUE TITLE
The Path Issue

### ISSUE THREAD

**Issue by loubean4073** [amarinderthind/decontaminer#3]
Hi,
I met a problem when I ran decontaMiner.sh. I just use your original databases and data(download from http://www-labgtp.na.icar.cnr.it/decontaminer/), but it said" ./Human_rna/rRNA.fasta, Human_rna/rRNA.idx is not an existing/valid absolute or relative path. I have checked the configure.txt, that's all right. Could you help me to solve the problem? Thank you so much!

**Comment by amarinderthind** [comment]
Hi, it should be path of the directory.... 

if 

fasta path   DB/HUMAN_RNA/rRNA.fasta
idx path      DB/HUMAN_RNA/rRNA.idx
  

Names you should mention following for configuration file : 

RIBO_DB=DB/HUMAN_RNA
RIBO_NAME=rRNA

Let me know, if it doesn't solve your issue.

**Comment by loubean4073** [comment]
Thank you for your reply!  Actually, I strictly follow the User Guide.pdf for setting up the config file.
Here is my running log in terminal showed below, and I notice that except the error I mentioned yesterday, the last sentence shows that: 

Wrong filepath or input file not existent: /home/kc/workspace/output/INTERMEDIATE_FILES/RIBO/unmapped_1_RIBO_UNALIGNED.fasta. 

And I check the RIBO folder, It's really empty there. It means that there is anything to be written in this folder.
Looking forward to your reply.

----------------------------------
bash ./decontaMiner.sh -i /home/kc/workspace/fasta/data_test/website_examples -o /home/kc/workspace/output -c /home/kc/decontaMiner_1.4/config_files/configure.txt

 -- WELCOME TO THE DECONTAMINER PIPELINE --

INFO: input file format (-f) not specified. BAM assumed
INFO: paired/single end flag -s not specified. PAIRED END assumed  (default option).
INFO: quality filtering flag -Q not specified. Quality filtering is ACTIVE (default option).
INFO: ribosomal filtering flag -R not specified. Human ribosomal filtering is ACTIVE (default option).

- PROCESSING DETAILS 
INFO: processing input in BAM format
INFO: processing PAIRED END data.
   INFO: quality encoding (-e ) not specified. Default:  33 
   INFO: percentage threshold (-p)  not specified. Default: 100  
   INFO: quality value threshold (-q)  not specified. Default: 20 
INFO: no option was specified for contaminating organisms. Assuming all (BACTERIA/FUNGI/VIRUSES, -bfv)

- LOADING AND CHECKING THE CONFIGURATION FILE : 
INFO: configuration file is: /home/kc/decontaMiner_1.4/config_files/configure.txt

 EXTERNAL SOFTWARE
  INFO: samtools executable is located at /usr/bin/samtools
  INFO: fastx executable is located at /usr/bin/fastq_quality_filter
  INFO: sortmerna executable is located at /home/kc/miniconda3/bin/sortmerna
  INFO: blastn executable is located at /home/kc/ncbi-blast-2.12.0+/bin/blastn

 HUMAN RIBOSOMAL/MITOCHONDRIAL DNA
  INFO: the ribosomal database rRNA (fasta + indexes) is located at /home/kc/workspace/fasta/Human_rna

 CONTAMINATING ORGANISMS DATABASES
  INFO: the bacteria database named Bacteria is located at /home/kc/workspace/fasta/BACTERIA_db
  INFO: the fungi database named Fungi is located at /home/kc/workspace/fasta/FUNGI_db
  INFO: the viruses database named Virus is located at /home/kc/workspace/fasta/VIRUSES_db

- PROCESSING STARTED   
INFO: executable files will be stored in the temporary directory: /home/kc/decontaMiner_1.4/shell_scripts/TEMP
INFO: results will be stored in the output directory: /home/kc/workspace/output/RESULTS
INFO: intermediate files results will be stored in the output directory: /home/kc/workspace/output/INTERMEDIATE_FILES
INFO: fasta files will be stored in the output directory: /home/kc/workspace/output/INTERMEDIATE_FILES/FASTA_FILES
INFO: fastq files will be stored in the output directory: /home/kc/workspace/output/INTERMEDIATE_FILES/FASTQ_FILES
INFO: fastq files will be stored in the output directory: /home/kc/workspace/output/INTERMEDIATE_FILES/FASTQ_FILES
 INFO: sorting the bam file. Please wait, this might take some time...
        done. Output file written in dir /home/kc/workspace/output/INTERMEDIATE_FILES/SORTED/unmapped_1.qsort
 INFO: converting to fastq ...
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 1896735 reads
        done. Output file written in dir /home/kc/workspace/output/INTERMEDIATE_FILES/FASTQ_FILES/unmapped_1.fastq
              Skipped reads (if present) written in dir /home/kc/workspace/output/INTERMEDIATE_FILES/SORTED/unmapped_1_SKIPPED.fastq
 INFO:  processing fastaQ  /home/kc/workspace/output/INTERMEDIATE_FILES/FASTQ_FILES/unmapped_1.fastq 
 INFO: quality filtering the fastq files  with nucleotide quality: 20, percentage: 100, encoding: 33 .
 done. Output files written in dir /home/kc/workspace/output/INTERMEDIATE_FILES/FASTQ_FILES/unmapped_1_Q.fastq
 INFO: converting to fasta format...
 ...done. Output file written in dir 
 INFO: extracting ribosomal RNA...
[process:1376] === Options processing starts ... ===
Found value: /home/kc/miniconda3/bin/sortmerna
Found flag: --ref
Found value: /home/kc/workspace/fasta/Human_rna/rRNA.fasta,/home/kc/workspace/fasta/Human_rna/rRNA.idx of previous flag: --ref
Found flag: --reads
Found value: /home/kc/workspace/output/INTERMEDIATE_FILES/FASTA_FILES/unmapped_1.fasta of previous flag: --reads
Found flag: --blast
Found value: 1 cigar qcov of previous flag: --blast
Found flag: --aligned
Found value: /home/kc/workspace/output/INTERMEDIATE_FILES/RIBO/unmapped_1_RIBO_ALIGNED of previous flag: --aligned
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --other
Found value: /home/kc/workspace/output/INTERMEDIATE_FILES/RIBO/unmapped_1_RIBO_UNALIGNED of previous flag: --other
Found value: fasta
Found flag: --paired_out
Previous flag: --paired_out is Boolean. Setting to True
Found flag: -e
Found value: 0.0000000000000000000000000000001 of previous flag: -e
[process:1460] Processing option: aligned with value: /home/kc/workspace/output/INTERMEDIATE_FILES/RIBO/unmapped_1_RIBO_ALIGNED
[process:1460] Processing option: blast with value: 1 cigar qcov
[process:1460] Processing option: e with value: 0.0000000000000000000000000000001
[process:1460] Processing option: fastx with value: 
[process:1460] Processing option: other with value: /home/kc/workspace/output/INTERMEDIATE_FILES/RIBO/unmapped_1_RIBO_UNALIGNED
[process:1460] Processing option: paired_out with value: 
[process:1460] Processing option: reads with value: /home/kc/workspace/output/INTERMEDIATE_FILES/FASTA_FILES/unmapped_1.fasta
[opt_reads:97] Processing reads file [1] out of total [1] files
[process:1460] Processing option: ref with value: /home/kc/workspace/fasta/Human_rna/rRNA.fasta,/home/kc/workspace/fasta/Human_rna/rRNA.idx
[opt_ref:157] Processing reference [1] out of total [1] references

[opt_ref:194] ERROR: The file /home/kc/workspace/fasta/Human_rna/rRNA.fasta,/home/kc/workspace/fasta/Human_rna/rRNA.idx is not an existing/valid absolute or relative path
Reference file (FASTA) absolute or relative path.

       Use mutliple times, once per a reference file


 done. Output written in /home/kc/workspace/output/INTERMEDIATE_FILES/RIBO/unmapped_1_RIBO_UNALIGNED
Wrong filepath or input file not existent:/home/kc/workspace/output/INTERMEDIATE_FILES/RIBO/unmapped_1_RIBO_UNALIGNED.fasta
----------------------------------

**Comment by amarinderthind** [comment]
Are you using 'test_data.tar.gz' as an input? Here I am sharing the configuration file that I have tested recently ..   

```
; Decontaminer configuration file. 

; Section 1: ext_soft.  Paths to the executables of external softwares.

[ext_soft]

; SAMTOOLS INSTALLED EXECUTABLE PATH (for samtool sort, bam2fq)
SAMTOOLS_EXEC= /home/software/samtools-1.3.1/samtools

; FASTX fastq_quality_filter EXECUTABLE PATH (for fastq_quality_filter)
FASTX_EXEC=  /scratch/hm82/CSCC/longRNA/unmapped/decontaMiner_1.4/fastx/fastq_quality_filter

; BLASTN INSTALLED EXECUTABLE PATH(for megablast)
BLASTN_EXEC= /scratch/hm82/CSCC/longRNA/unmapped/decontaMiner_1.4/ncbi-blast-2.2.29+/bin/blastn

; SORTMERNA INSTALLED EXECUTABLE PATH 
SORTMERNA_EXEC = /scratch/hm82/CSCC/longRNA/unmapped/decontaMiner_1.4/sortmerna-2.1b/sortmerna

; Section 2: cont_db.  Paths to the databases of contaminating sequences

[cont_db]

; HUMAN RIBOSOMAL SEQUENCES, SORTEMERNA FORMAT
; PATH OF THE DIRECTORY CONTAINING THE FASTA FILE (.fasta) AND THE INDEXES (.idx*)
RIBO_DB=/scratch/unmapped/decontaMiner_1.4/DB/HUMAN_RNA
; NAME OF THE DB ([name].fasta AND INDEXES  ([name].idx*)
RIBO_NAME=rRNA

; DATABASE OF BACTERIA, BLAST FORMAT
; PATH OF THE DIRECTORY CONTAINING THE COMPRESSED FILES
BACTERIA_DB=/scratch/unmapped/decontaMiner_1.4/DB/BACTERIA
BACTERIA_NAME=Bacteria_newblast

; DATABASE OF FUNGI, BLAST FORMAT
; PATH OF THE DIRECTORY CONTAINING THE COMPRESSED FILES
FUNGI_DB=/scratch/unmapped/decontaMiner_1.4/DB/FUNGI

FUNGI_NAME=Fungi_new

; DATABASE OF VIRUSES, BLAST FORMAT
; PATH OF THE DIRECTORY CONTAINING THE COMPRESSED FILES
VIRUSES_DB=/scratch/unmapped/decontaMiner_1.4/DB/VIRUSES

VIRUSES_NAME=Virus_new
```

**Comment by loubean4073** [comment]
Hi, thank you for providing your configure.txt for reference. According to your configure.txt, I found that the version of the software tools I use is different from yours. So I reinstalled all the software tools to your version. It works now. 
Thanks again!

**Comment by amarinderthind** [comment]
That's great.
